Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
await in (anonymous)
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
(anonymous) @ index-yZFP6s64.js:40
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
set fillColor @ (unknown)
onHueSliderUpdate_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
setX @ (unknown)
shiftX @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerDown @ (unknown)
onHueSliderMouseDown_ @ (unknown)
await in onHueSliderMouseDown_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
set fillColor @ (unknown)
onHueSliderUpdate_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
setX @ (unknown)
shiftX @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerDown @ (unknown)
onHueSliderMouseDown_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerDown @ (unknown)
onColorWellMouseDown_ @ (unknown)
await in onColorWellMouseDown_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerDown @ (unknown)
onColorWellMouseDown_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
(anonymous) @ index-yZFP6s64.js:95
(anonymous) @ index-yZFP6s64.js:95
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
await in onMouseMove_
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:67
QA @ index-yZFP6s64.js:67
invoke @ index-yZFP6s64.js:67
(anonymous) @ index-yZFP6s64.js:280
gp @ index-yZFP6s64.js:40
ha @ index-yZFP6s64.js:40
EI @ index-yZFP6s64.js:40
Ts @ index-yZFP6s64.js:40
ox @ index-yZFP6s64.js:40
ds @ index-yZFP6s64.js:38
to @ index-yZFP6s64.js:40
zj @ index-yZFP6s64.js:37
Pm @ index-yZFP6s64.js:37
Ey @ index-yZFP6s64.js:37
p6 @ index-yZFP6s64.js:37
onVisualColorChange_ @ (unknown)
onColorSelectionRingUpdate_ @ (unknown)
updateColor @ (unknown)
onPositionChange_ @ (unknown)
set @ (unknown)
moveTo @ (unknown)
moveColorSelectionRingTo_ @ (unknown)
pointerMove @ (unknown)
onMouseMove_ @ (unknown)
calendar:1 Access to fetch at 'https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write' from origin 'https://app.opsiscx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
index-yZFP6s64.js:95  POST https://dqvuviyqrcrgapmxkoyx.supabase.co/functions/v1/google-calendar-write net::ERR_FAILED
